# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slider.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(889, 300)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(320, 120, 160, 22))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: none;\n"
"    height: 3.5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {    \n"
"\n"
"}\n"
"\n"
"QSlider::groove:horizontal:hover QSlider::handle:horizontal {\n"
"            background: #fff;\n"
"        width: 13px;\n"
"        margin: -7px 8px;\n"
"        border-radius: 7.5px;\n"
"        border: 2px solid #BFBFBF\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #E5E5E5\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #737373\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
