# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'thelastWqTyKO.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *
from Item import Item

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1440, 900)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.container = QFrame(self.centralwidget)
        self.container.setObjectName(u"container")
        self.container.setGeometry(QRect(0, 0, 1440, 900))
        self.container.setStyleSheet(u"background-color: #fff;\n"
"border-radius: 6px")
        self.container.setFrameShape(QFrame.StyledPanel)
        self.container.setFrameShadow(QFrame.Raised)
        self.sidebar_2 = QFrame(self.container)
        self.sidebar_2.setObjectName(u"sidebar_2")
        self.sidebar_2.setGeometry(QRect(0, 0, 221, 900))
        self.sidebar_2.setStyleSheet(u"background-color: #EAEAEA; \n"
"border-radius: 0px;\n"
"border-top-left-radius: 6px; \n"
"border-bottom-left-radius: 6px")
        self.sidebar_2.setFrameShape(QFrame.StyledPanel)
        self.sidebar_2.setFrameShadow(QFrame.Raised)
        self.AppleMusic_3 = QFrame(self.sidebar_2)
        self.AppleMusic_3.setObjectName(u"AppleMusic_3")
        self.AppleMusic_3.setGeometry(QRect(10, 146, 200, 120))
        self.AppleMusic_3.setFrameShape(QFrame.StyledPanel)
        self.AppleMusic_3.setFrameShadow(QFrame.Raised)
        self.pushButton_ListenNow = QPushButton(self.AppleMusic_3)
        self.pushButton_ListenNow.setObjectName(u"pushButton_ListenNow")
        self.pushButton_ListenNow.setGeometry(QRect(0, 0, 200, 28))
        self.pushButton_ListenNow.setSizeIncrement(QSize(0, 0))
        self.pushButton_ListenNow.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setFamily(u"SF Pro Display")
        font.setPointSize(10)
        self.pushButton_ListenNow.setFont(font)
        self.pushButton_ListenNow.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_ListenNow.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_ListenNow.setStyleSheet(u"border-radius: 6px;\n"
"text-align: left;\n"
"padding-left: 16px;\n"
"background-color: #C8C8C8;")
        icon = QIcon()
        icon.addFile(u"./images/ListenNow.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_ListenNow.setIcon(icon)
        self.pushButton_ListenNow.setIconSize(QSize(16, 16))
        self.pushButton_ListenNow.setCheckable(False)
        self.pushButton_ListenNow.setAutoDefault(False)
        self.pushButton_ListenNow.setFlat(False)
        self.pushButton_Favourite = QPushButton(self.AppleMusic_3)
        self.pushButton_Favourite.setObjectName(u"pushButton_Favourite")
        self.pushButton_Favourite.setGeometry(QRect(0, 30, 200, 28))
        self.pushButton_Favourite.setSizeIncrement(QSize(0, 0))
        self.pushButton_Favourite.setBaseSize(QSize(0, 0))
        self.pushButton_Favourite.setFont(font)
        self.pushButton_Favourite.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_Favourite.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_Favourite.setStyleSheet(u"border-radius: 6px;\n"
"text-align: left;\n"
"padding-left: 16px;\n"
"")
        icon1 = QIcon()
        icon1.addFile(u"./images/Music.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_Favourite.setIcon(icon1)
        self.pushButton_Favourite.setIconSize(QSize(16, 16))
        self.pushButton_Favourite.setCheckable(False)
        self.pushButton_Favourite.setAutoDefault(False)
        self.pushButton_Favourite.setFlat(False)
        self.pushButton_Album = QPushButton(self.AppleMusic_3)
        self.pushButton_Album.setObjectName(u"pushButton_Album")
        self.pushButton_Album.setGeometry(QRect(0, 60, 200, 28))
        self.pushButton_Album.setSizeIncrement(QSize(0, 0))
        self.pushButton_Album.setBaseSize(QSize(0, 0))
        self.pushButton_Album.setFont(font)
        self.pushButton_Album.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_Album.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_Album.setStyleSheet(u"border-radius: 6px;\n"
"text-align: left;\n"
"padding-left: 16px;\n"
"")
        icon2 = QIcon()
        icon2.addFile(u"./images/Album.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_Album.setIcon(icon2)
        self.pushButton_Album.setIconSize(QSize(16, 16))
        self.pushButton_Album.setCheckable(False)
        self.pushButton_Album.setAutoDefault(False)
        self.pushButton_Album.setFlat(False)
        self.pushButton_Album_2 = QPushButton(self.AppleMusic_3)
        self.pushButton_Album_2.setObjectName(u"pushButton_Album_2")
        self.pushButton_Album_2.setGeometry(QRect(0, 90, 200, 28))
        self.pushButton_Album_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_Album_2.setBaseSize(QSize(0, 0))
        self.pushButton_Album_2.setFont(font)
        self.pushButton_Album_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_Album_2.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_Album_2.setStyleSheet(u"border-radius: 6px;\n"
"text-align: left;\n"
"padding-left: 16px;\n"
"")
        self.pushButton_Album_2.setIcon(icon)
        self.pushButton_Album_2.setIconSize(QSize(16, 16))
        self.pushButton_Album_2.setCheckable(False)
        self.pushButton_Album_2.setAutoDefault(False)
        self.pushButton_Album_2.setFlat(False)
        self.window = QFrame(self.sidebar_2)
        self.window.setObjectName(u"window")
        self.window.setGeometry(QRect(20, 20, 52, 12))
        self.window.setFrameShape(QFrame.StyledPanel)
        self.window.setFrameShadow(QFrame.Raised)
        self.TrafficLight_ED695E_6 = QPushButton(self.window)
        self.TrafficLight_ED695E_6.setObjectName(u"TrafficLight_ED695E_6")
        self.TrafficLight_ED695E_6.setGeometry(QRect(0, 0, 12, 12))
        self.TrafficLight_ED695E_6.setStyleSheet(u"border: 0.5px solid #D14C3E;\n"
"background-color: #ED695E;\n"
"border-radius: 6px")
        self.TrafficLight_F7BE4F_5 = QPushButton(self.window)
        self.TrafficLight_F7BE4F_5.setObjectName(u"TrafficLight_F7BE4F_5")
        self.TrafficLight_F7BE4F_5.setGeometry(QRect(20, 0, 12, 12))
        self.TrafficLight_F7BE4F_5.setStyleSheet(u"border: 0.5px solid #D9A651;\n"
"background-color: #F7BE4F;\n"
"border-radius: 6px")
        self.TrafficLight_62C554_5 = QPushButton(self.window)
        self.TrafficLight_62C554_5.setObjectName(u"TrafficLight_62C554_5")
        self.TrafficLight_62C554_5.setGeometry(QRect(40, 0, 12, 12))
        self.TrafficLight_62C554_5.setStyleSheet(u"border: 0.5px solid #4FA53A;\n"
"background-color: #62C554;\n"
"border-radius: 6px")
        self.label_85 = QLabel(self.sidebar_2)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(15, 122, 91, 16))
        font1 = QFont()
        font1.setFamily(u"SF Pro Display")
        font1.setPointSize(9)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_85.setFont(font1)
        self.label_85.setStyleSheet(u"color: #9F9E9B")
        self.frameSearch = QFrame(self.sidebar_2)
        self.frameSearch.setObjectName(u"frameSearch")
        self.frameSearch.setGeometry(QRect(11, 62, 199, 28))
        self.frameSearch.setStyleSheet(u"background-color: #DFDFDF;\n"
"border: 0.5px solid #C8C6C4;\n"
"border-radius: 6px")
        self.frameSearch.setFrameShape(QFrame.StyledPanel)
        self.frameSearch.setFrameShadow(QFrame.Raised)
        self.label_86 = QLabel(self.frameSearch)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(9, 4, 20, 21))
        self.label_86.setStyleSheet(u"border:none")
        self.label_86.setPixmap(QPixmap(u"./images/Search.svg"))
        self.label_86.setScaledContents(False)
        self.label_86.setAlignment(Qt.AlignCenter)
        self.lineEditSearch = QLineEdit(self.frameSearch)
        self.lineEditSearch.setObjectName(u"lineEditSearch")
        self.lineEditSearch.setGeometry(QRect(34, 6, 150, 17))
        font2 = QFont()
        font2.setFamily(u"SF Pro Display")
        font2.setPointSize(9)
        font2.setBold(False)
        font2.setWeight(50)
        self.lineEditSearch.setFont(font2)
        self.lineEditSearch.setStyleSheet(u"border: none;\n"
"background-color: transparent;\n"
"QLineEdit[text=\\\"\\\"] { \n"
"	color:red;\n"
"}")
        self.label_87 = QLabel(self.sidebar_2)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(15, 310, 91, 16))
        self.label_87.setFont(font1)
        self.label_87.setStyleSheet(u"color: #9F9E9B")
        self.frame_Playlist = QFrame(self.sidebar_2)
        self.frame_Playlist.setObjectName(u"frame_Playlist")
        self.frame_Playlist.setGeometry(QRect(10, 340, 228, 90))
        self.frame_Playlist.setFrameShape(QFrame.StyledPanel)
        self.frame_Playlist.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.frame_Playlist)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.pushButton_Album_3 = QPushButton(self.frame_Playlist)
        self.pushButton_Album_3.setObjectName(u"pushButton_Album_3")
        self.pushButton_Album_3.setSizeIncrement(QSize(0, 0))
        self.pushButton_Album_3.setBaseSize(QSize(0, 0))
        self.pushButton_Album_3.setFont(font)
        self.pushButton_Album_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_Album_3.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_Album_3.setStyleSheet(u"border-radius: 6px;\n"
"text-align: left;\n"
"padding-left: 16px;\n"
"")
        icon3 = QIcon()
        icon3.addFile(u"./images/playlist.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_Album_3.setIcon(icon3)
        self.pushButton_Album_3.setIconSize(QSize(16, 16))
        self.pushButton_Album_3.setCheckable(False)
        self.pushButton_Album_3.setAutoDefault(False)
        self.pushButton_Album_3.setFlat(False)

        self.verticalLayout.addWidget(self.pushButton_Album_3)

        self.pushButton_Album_4 = QPushButton(self.frame_Playlist)
        self.pushButton_Album_4.setObjectName(u"pushButton_Album_4")
        self.pushButton_Album_4.setSizeIncrement(QSize(0, 0))
        self.pushButton_Album_4.setBaseSize(QSize(0, 0))
        self.pushButton_Album_4.setFont(font)
        self.pushButton_Album_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_Album_4.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_Album_4.setStyleSheet(u"border-radius: 6px;\n"
"text-align: left;\n"
"padding-left: 16px;\n"
"")
        self.pushButton_Album_4.setIcon(icon3)
        self.pushButton_Album_4.setIconSize(QSize(16, 16))
        self.pushButton_Album_4.setCheckable(False)
        self.pushButton_Album_4.setAutoDefault(False)
        self.pushButton_Album_4.setFlat(False)

        self.verticalLayout.addWidget(self.pushButton_Album_4)

        self.pushButton_Album_5 = QPushButton(self.frame_Playlist)
        self.pushButton_Album_5.setObjectName(u"pushButton_Album_5")
        self.pushButton_Album_5.setSizeIncrement(QSize(0, 0))
        self.pushButton_Album_5.setBaseSize(QSize(0, 0))
        self.pushButton_Album_5.setFont(font)
        self.pushButton_Album_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_Album_5.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_Album_5.setStyleSheet(u"border-radius: 6px;\n"
"text-align: left;\n"
"padding-left: 16px;\n"
"")
        self.pushButton_Album_5.setIcon(icon3)
        self.pushButton_Album_5.setIconSize(QSize(16, 16))
        self.pushButton_Album_5.setCheckable(False)
        self.pushButton_Album_5.setAutoDefault(False)
        self.pushButton_Album_5.setFlat(False)

        self.verticalLayout.addWidget(self.pushButton_Album_5)

        self.mainlayout = QFrame(self.container)
        self.mainlayout.setObjectName(u"mainlayout")
        self.mainlayout.setGeometry(QRect(221, 52, 1219, 796))
        self.mainlayout.setFrameShape(QFrame.StyledPanel)
        self.mainlayout.setFrameShadow(QFrame.Raised)
        self.stackedWidget = QStackedWidget(self.mainlayout)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 1219, 796))
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.imageAlbum = QLabel(self.page_3)
        self.imageAlbum.setObjectName(u"imageAlbum")
        self.imageAlbum.setGeometry(QRect(50, 48, 270, 270))
        self.imageAlbum.setPixmap(QPixmap(u"./images/Hiphop.png"))
        self.imageAlbum.setAlignment(Qt.AlignCenter)
        self.nameAlbum = QLabel(self.page_3)
        self.nameAlbum.setObjectName(u"nameAlbum")
        self.nameAlbum.setGeometry(QRect(352, 48, 481, 29))
        font3 = QFont()
        font3.setFamily(u"SF Pro Display")
        font3.setPointSize(16)
        self.nameAlbum.setFont(font3)
        self.applemusic = QLabel(self.page_3)
        self.applemusic.setObjectName(u"applemusic")
        self.applemusic.setGeometry(QRect(352, 85, 481, 29))
        self.applemusic.setFont(font3)
        self.applemusic.setStyleSheet(u"color: #F7C74E")
        self.des = QLabel(self.page_3)
        self.des.setObjectName(u"des")
        self.des.setGeometry(QRect(352, 194, 440, 51))
        self.des.setFont(font2)
        self.des.setStyleSheet(u"color: #808080")
        self.des.setWordWrap(True)
        self.playButton = QPushButton(self.page_3)
        self.playButton.setObjectName(u"playButton")
        self.playButton.setGeometry(QRect(352, 270, 153, 28))
        self.playButton.setFont(font1)
        self.playButton.setStyleSheet(u"border: none;\n"
"border-radius: 3px;\n"
"background-color: #F8C84E;\n"
"color: #fff")
        icon4 = QIcon()
        icon4.addFile(u"./images/play_white.png", QSize(), QIcon.Normal, QIcon.Off)
        self.playButton.setIcon(icon4)
        self.continue_2 = QLabel(self.page_3)
        self.continue_2.setObjectName(u"continue_2")
        self.continue_2.setGeometry(QRect(802, 228, 61, 16))
        font4 = QFont()
        font4.setFamily(u"SF Pro Display")
        font4.setPointSize(9)
        self.continue_2.setFont(font4)
        self.continue_2.setStyleSheet(u"color: #F8C84E")
        self.shuffleButton = QPushButton(self.page_3)
        self.shuffleButton.setObjectName(u"shuffleButton")
        self.shuffleButton.setGeometry(QRect(515, 270, 153, 28))
        self.shuffleButton.setFont(font1)
        self.shuffleButton.setStyleSheet(u"border: none;\n"
"border-radius: 3px;\n"
"background-color: #F8C84E;\n"
"color: #fff")
        icon5 = QIcon()
        icon5.addFile(u"./images/shuffle_white.png", QSize(), QIcon.Normal, QIcon.Off)
        self.shuffleButton.setIcon(icon5)
        self.titlebar = QFrame(self.page_3)
        self.titlebar.setObjectName(u"titlebar")
        self.titlebar.setGeometry(QRect(98, 357, 1117, 16))
        self.titlebar.setFrameShape(QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QFrame.Raised)
        self.label_5 = QLabel(self.titlebar)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 111, 16))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: #808080")
        self.label_6 = QLabel(self.titlebar)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(455, 0, 111, 16))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"color: #808080")
        self.label_7 = QLabel(self.titlebar)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(755, 0, 111, 16))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: #808080")
        self.label_8 = QLabel(self.titlebar)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(1031, 0, 111, 16))
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(u"color: #808080")
        self.listsong = QFrame(self.page_3)
        self.listsong.setObjectName(u"listsong")
        self.listsong.setGeometry(QRect(24, 381, 1160, 400))
        self.listsong.setFrameShape(QFrame.StyledPanel)
        self.listsong.setFrameShadow(QFrame.Raised)
        self.frame_2 = QFrame(self.listsong)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 0, 1160, 55))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_44 = QLabel(self.frame_2)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(529, 17, 151, 16))
        font5 = QFont()
        font5.setFamily(u"SF Pro Text")
        font5.setPointSize(9)
        self.label_44.setFont(font5)
        self.label_44.setStyleSheet(u"color: #7e7e7e")
        self.label_45 = QLabel(self.frame_2)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(25, 7, 40, 40))
        self.label_45.setStyleSheet(u"border-radius: 5px")
        self.label_45.setPixmap(QPixmap(u"./images/GoingBad.png"))
        self.label_45.setAlignment(Qt.AlignCenter)
        self.label_46 = QLabel(self.frame_2)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(498, 20, 12, 10))
        self.label_46.setPixmap(QPixmap(u"./images/e.png"))
        self.label_46.setAlignment(Qt.AlignCenter)
        self.label_47 = QLabel(self.frame_2)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(1105, 17, 55, 16))
        self.label_47.setFont(font5)
        self.label_47.setStyleSheet(u"color: #7e7e7e")
        self.label_48 = QLabel(self.frame_2)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(74, 17, 271, 21))
        font6 = QFont()
        font6.setFamily(u"SF Pro Text")
        font6.setPointSize(10)
        self.label_48.setFont(font6)
        self.label_48.setStyleSheet(u"")
        self.label_49 = QLabel(self.frame_2)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(830, 17, 261, 21))
        self.label_49.setFont(font6)
        self.label_49.setStyleSheet(u"color: #7e7e7e")
        self.item = QFrame(self.listsong)
        self.item.setObjectName(u"item")
        self.item.setGeometry(QRect(0, 55, 1160, 55))
        self.item.setFrameShape(QFrame.StyledPanel)
        self.item.setFrameShadow(QFrame.Raised)
        self.label_50 = QLabel(self.item)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(529, 17, 151, 16))
        self.label_50.setFont(font5)
        self.label_50.setStyleSheet(u"color: #7e7e7e")
        self.label_51 = QLabel(self.item)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(25, 7, 40, 40))
        self.label_51.setStyleSheet(u"border-radius: 5px")
        self.label_51.setPixmap(QPixmap(u"./images/HighestInTheRoom.png"))
        self.label_51.setAlignment(Qt.AlignCenter)
        self.label_52 = QLabel(self.item)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(498, 20, 12, 10))
        self.label_52.setPixmap(QPixmap(u"./images/e.png"))
        self.label_52.setAlignment(Qt.AlignCenter)
        self.label_53 = QLabel(self.item)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(1105, 17, 55, 16))
        self.label_53.setFont(font5)
        self.label_53.setStyleSheet(u"color: #7e7e7e")
        self.label_54 = QLabel(self.item)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(74, 17, 271, 21))
        self.label_54.setFont(font6)
        self.label_54.setStyleSheet(u"")
        self.label_55 = QLabel(self.item)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(830, 17, 261, 21))
        self.label_55.setFont(font6)
        self.label_55.setStyleSheet(u"color: #7e7e7e")
        self.frame_21 = QFrame(self.listsong)
        self.frame_21.setObjectName(u"frame_21")
        self.frame_21.setGeometry(QRect(0, 110, 1160, 55))
        self.frame_21.setFrameShape(QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.label_56 = QLabel(self.frame_21)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(529, 17, 151, 16))
        self.label_56.setFont(font5)
        self.label_56.setStyleSheet(u"color: #7e7e7e")
        self.label_57 = QLabel(self.frame_21)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(25, 7, 40, 40))
        self.label_57.setStyleSheet(u"border-radius: 5px")
        self.label_57.setPixmap(QPixmap(u"./images/PraiseTheLord.png"))
        self.label_57.setAlignment(Qt.AlignCenter)
        self.label_58 = QLabel(self.frame_21)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(498, 20, 12, 10))
        self.label_58.setPixmap(QPixmap(u"./images/e.png"))
        self.label_58.setAlignment(Qt.AlignCenter)
        self.label_59 = QLabel(self.frame_21)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(1105, 17, 55, 16))
        self.label_59.setFont(font5)
        self.label_59.setStyleSheet(u"color: #7e7e7e")
        self.label_60 = QLabel(self.frame_21)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(74, 17, 271, 21))
        self.label_60.setFont(font6)
        self.label_60.setStyleSheet(u"")
        self.label_61 = QLabel(self.frame_21)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(830, 17, 261, 21))
        self.label_61.setFont(font6)
        self.label_61.setStyleSheet(u"color: #7e7e7e")
        self.frame_22 = QFrame(self.listsong)
        self.frame_22.setObjectName(u"frame_22")
        self.frame_22.setGeometry(QRect(0, 165, 1160, 55))
        self.frame_22.setFrameShape(QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.label_62 = QLabel(self.frame_22)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(529, 17, 151, 16))
        self.label_62.setFont(font5)
        self.label_62.setStyleSheet(u"color: #7e7e7e")
        self.label_63 = QLabel(self.frame_22)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(25, 7, 40, 40))
        self.label_63.setStyleSheet(u"border-radius: 5px")
        self.label_63.setPixmap(QPixmap(u"./images/Taste.png"))
        self.label_63.setAlignment(Qt.AlignCenter)
        self.label_64 = QLabel(self.frame_22)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(498, 20, 12, 10))
        self.label_64.setPixmap(QPixmap(u"./images/e.png"))
        self.label_64.setAlignment(Qt.AlignCenter)
        self.label_65 = QLabel(self.frame_22)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(1105, 17, 55, 16))
        self.label_65.setFont(font5)
        self.label_65.setStyleSheet(u"color: #7e7e7e")
        self.label_66 = QLabel(self.frame_22)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(74, 17, 271, 21))
        self.label_66.setFont(font6)
        self.label_66.setStyleSheet(u"")
        self.label_67 = QLabel(self.frame_22)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(830, 17, 261, 21))
        self.label_67.setFont(font6)
        self.label_67.setStyleSheet(u"color: #7e7e7e")
        self.frame_23 = QFrame(self.listsong)
        self.frame_23.setObjectName(u"frame_23")
        self.frame_23.setGeometry(QRect(0, 220, 1160, 55))
        self.frame_23.setFrameShape(QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QFrame.Raised)
        self.label_68 = QLabel(self.frame_23)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(529, 17, 151, 16))
        self.label_68.setFont(font5)
        self.label_68.setStyleSheet(u"color: #7e7e7e")
        self.label_69 = QLabel(self.frame_23)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(25, 7, 40, 40))
        self.label_69.setStyleSheet(u"border-radius: 5px")
        self.label_69.setPixmap(QPixmap(u"./images/Wow.png"))
        self.label_69.setAlignment(Qt.AlignCenter)
        self.label_70 = QLabel(self.frame_23)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(498, 20, 12, 10))
        self.label_70.setPixmap(QPixmap(u"./images/e.png"))
        self.label_70.setAlignment(Qt.AlignCenter)
        self.label_71 = QLabel(self.frame_23)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(1105, 17, 55, 16))
        self.label_71.setFont(font5)
        self.label_71.setStyleSheet(u"color: #7e7e7e")
        self.label_72 = QLabel(self.frame_23)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(74, 17, 271, 21))
        self.label_72.setFont(font6)
        self.label_72.setStyleSheet(u"")
        self.label_73 = QLabel(self.frame_23)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(830, 17, 261, 21))
        self.label_73.setFont(font6)
        self.label_73.setStyleSheet(u"color: #7e7e7e")
        self.frame_24 = QFrame(self.listsong)
        self.frame_24.setObjectName(u"frame_24")
        self.frame_24.setGeometry(QRect(0, 275, 1160, 55))
        self.frame_24.setFrameShape(QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.label_74 = QLabel(self.frame_24)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(529, 17, 151, 16))
        self.label_74.setFont(font5)
        self.label_74.setStyleSheet(u"color: #7e7e7e")
        self.label_75 = QLabel(self.frame_24)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(25, 7, 40, 40))
        self.label_75.setStyleSheet(u"border-radius: 5px")
        self.label_75.setPixmap(QPixmap(u"./images/679s.png"))
        self.label_75.setAlignment(Qt.AlignCenter)
        self.label_76 = QLabel(self.frame_24)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(498, 20, 12, 10))
        self.label_76.setPixmap(QPixmap(u"./images/e.png"))
        self.label_76.setAlignment(Qt.AlignCenter)
        self.label_77 = QLabel(self.frame_24)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(1105, 17, 55, 16))
        self.label_77.setFont(font5)
        self.label_77.setStyleSheet(u"color: #7e7e7e")
        self.label_78 = QLabel(self.frame_24)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(74, 17, 271, 21))
        self.label_78.setFont(font6)
        self.label_78.setStyleSheet(u"")
        self.label_79 = QLabel(self.frame_24)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(830, 17, 261, 21))
        self.label_79.setFont(font6)
        self.label_79.setStyleSheet(u"color: #7e7e7e")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.titlebar_2 = QFrame(self.page_4)
        self.titlebar_2.setObjectName(u"titlebar_2")
        self.titlebar_2.setGeometry(QRect(98, 48, 1117, 16))
        self.titlebar_2.setFrameShape(QFrame.StyledPanel)
        self.titlebar_2.setFrameShadow(QFrame.Raised)
        self.label_9 = QLabel(self.titlebar_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 0, 111, 16))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color: #808080")
        self.label_10 = QLabel(self.titlebar_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(455, 0, 111, 16))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"color: #808080")
        self.label_11 = QLabel(self.titlebar_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(755, 0, 111, 16))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: #808080")
        self.label_12 = QLabel(self.titlebar_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(1031, 0, 111, 16))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: #808080")
        self.listsong_2 = QFrame(self.page_4)
        self.listsong_2.setObjectName(u"listsong_2")
        self.listsong_2.setGeometry(QRect(24, 72, 1160, 721))
        self.listsong_2.setMinimumSize(QSize(0, 721))
        self.listsong_2.setStyleSheet(u"")
        self.listsong_2.setFrameShape(QFrame.StyledPanel)
        self.listsong_2.setFrameShadow(QFrame.Raised)





        # ---------------------------------Add song----------------------------
        frame_container = self.listsong_2  # Container frame

        # layout = QVBoxLayout()
        # scroll = QScrollArea()

        # # Tạo một QWidget để chứa nội dung có thể scroll
        # scroll_content = QWidget()
        # scroll_layout = QVBoxLayout(scroll_content)
        # # Thêm các widget vào scroll layout
        # for i in range(10):
        #         my_item = Item()
        #         my_item.setupUi(frame_container)  # Cài đặt UI trên container frame
        #         scroll_layout.addWidget(my_item.item_frame)
        # # Thiết lập widget con cho scroll area
        # scroll.setWidget(scroll_content)
        # scroll.setWidgetResizable(True)
        # # Đặt kích thước cố định cho scroll area
        # scroll.setFixedHeight(721)

        # layout.addWidget(scroll)
        # layout.setContentsMargins(0, 0, 0, 0)
        # frame_container.setLayout(layout)


        gridSong = QGridLayout()
        frame_container.setLayout(gridSong)

        for i in range(0, 10):
            my_item = Item()
            my_item.setupUi(frame_container)
            gridSong.addWidget(my_item.item_frame, i, 0)
        gridSong.setRowStretch(8, 1)

        #     my_item = Item()
        #     my_item.setupUi(frame_container)
        #     gridSong.addWidget(my_item.item_frame, *positions)
        # gridSong.setRowStretch(5, 1)
        #     button = QPushButton(names)
        #     gridSong.addWidget(button, *positions)

        # ---------------------------Add song---------------------------------
        
        
        


        self.stackedWidget.addWidget(self.page_4)
        self.navbar_2 = QFrame(self.container)
        self.navbar_2.setObjectName(u"navbar_2")
        self.navbar_2.setGeometry(QRect(221, 0, 1219, 52))
        self.navbar_2.setStyleSheet(u"background-color: #F4F4F4; \n"
"border-radius: 0px; \n"
"border-top-right-radius: 6px")
        self.navbar_2.setFrameShape(QFrame.StyledPanel)
        self.navbar_2.setFrameShadow(QFrame.Raised)
        self.back_4 = QLabel(self.navbar_2)
        self.back_4.setObjectName(u"back_4")
        self.back_4.setGeometry(QRect(22, 15, 13, 21))
        self.back_4.setPixmap(QPixmap(u"./images/ChevronLeft.png"))
        self.back_4.setAlignment(Qt.AlignCenter)
        self.playlist_4 = QLabel(self.navbar_2)
        self.playlist_4.setObjectName(u"playlist_4")
        self.playlist_4.setGeometry(QRect(568, 17, 55, 16))
        self.playlist_4.setFont(font)
        self.playlist_4.setStyleSheet(u"color: #4A4A4A\n"
"")
        self.songbar_2 = QFrame(self.container)
        self.songbar_2.setObjectName(u"songbar_2")
        self.songbar_2.setGeometry(QRect(221, 848, 1219, 52))
        self.songbar_2.setStyleSheet(u"background-color: #fff; \n"
"border-radius: 0px; \n"
"border-bottom-right-radius: 6px")
        self.songbar_2.setFrameShape(QFrame.StyledPanel)
        self.songbar_2.setFrameShadow(QFrame.Raised)
        self.label_19 = QLabel(self.songbar_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(49, 17, 20, 16))
        self.label_19.setPixmap(QPixmap(u"./images/Shuffle.svg"))
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.songbar_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(185, 17, 20, 16))
        self.label_20.setPixmap(QPixmap(u"./images/Loop.svg"))
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(self.songbar_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(80, 16, 26, 19))
        self.label_21.setPixmap(QPixmap(u"./images/Prev.svg"))
        self.label_21.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(self.songbar_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(147, 16, 26, 19))
        self.label_22.setPixmap(QPixmap(u"./images/Next.svg"))
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.songbar_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(117, 13, 18, 26))
        self.label_23.setPixmap(QPixmap(u"./images/Resume.svg"))
        self.label_23.setAlignment(Qt.AlignCenter)
        self.frame_4 = QFrame(self.songbar_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(340, 0, 565, 52))
        self.frame_4.setStyleSheet(u"border-right: 0.5px solid #E0E0E0")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.label_24 = QLabel(self.frame_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 0, 51, 52))
        self.label_24.setPixmap(QPixmap(u"./images/\u0421\u043d\u0438\u043c\u043e\u043a \u044d\u043a\u0440\u0430\u043d\u0430 2021-06-16 \u0432 19.10 1.png"))
        self.label_24.setAlignment(Qt.AlignCenter)
        self.label_25 = QLabel(self.frame_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(83, 10, 401, 20))
        font7 = QFont()
        font7.setFamily(u"SF Pro Text")
        font7.setPointSize(9)
        font7.setBold(True)
        font7.setWeight(75)
        self.label_25.setFont(font7)
        self.label_25.setStyleSheet(u"color: #1B1B1B;\n"
"border: none")
        self.label_25.setAlignment(Qt.AlignCenter)
        self.label_26 = QLabel(self.frame_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(83, 30, 401, 20))
        self.label_26.setFont(font7)
        self.label_26.setStyleSheet(u"color: #808080;\n"
"border: none")
        self.label_26.setAlignment(Qt.AlignCenter)
        self.horizontalSlider = QSlider(self.frame_4)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(51, 0, 514, 3))
        self.horizontalSlider.setStyleSheet(u"QSlider::groove:horizontal {\n"
"	border: none;\n"
"	height: 3px;\n"
"	background: transparent\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"	background: #E5E5E5\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"	margin: -6px -7px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"	background: #737373\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.label_27 = QLabel(self.songbar_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(940, 15, 12, 14))
        self.label_27.setPixmap(QPixmap(u"./images/Min.svg"))
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_28 = QLabel(self.songbar_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(1024, 15, 20, 14))
        self.label_28.setPixmap(QPixmap(u"./images/Max.svg"))
        self.label_28.setAlignment(Qt.AlignCenter)
        self.volumeSlider = QSlider(self.songbar_2)
        self.volumeSlider.setObjectName(u"volumeSlider")
        self.volumeSlider.setGeometry(QRect(960, 10, 55, 22))
        self.volumeSlider.setStyleSheet(u"QSlider::groove:horizontal {\n"
"	border: none;\n"
"	height: 3px;\n"
"	background: transparent\n"
"}\n"
"\n"
"QSlider::handle:horizontal {	\n"
"		background: #fff;\n"
"		width: 13px;\n"
"		margin: -7px 0px;\n"
"		border-radius: 7.5px;\n"
"		border: 2px solid #BFBFBF\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"	background: #E5E5E5\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"	background: #737373\n"
"}\n"
"")
        self.volumeSlider.setOrientation(Qt.Horizontal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.pushButton_ListenNow.setDefault(False)
        self.pushButton_Favourite.setDefault(False)
        self.pushButton_Album.setDefault(False)
        self.pushButton_Album_2.setDefault(False)
        self.pushButton_Album_3.setDefault(False)
        self.pushButton_Album_4.setDefault(False)
        self.pushButton_Album_5.setDefault(False)
        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_ListenNow.setText(QCoreApplication.translate("MainWindow", u"Listen Now", None))
        self.pushButton_Favourite.setText(QCoreApplication.translate("MainWindow", u"Favourite", None))
        self.pushButton_Album.setText(QCoreApplication.translate("MainWindow", u"Playlist", None))
        self.pushButton_Album_2.setText(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.TrafficLight_ED695E_6.setText("")
        self.TrafficLight_F7BE4F_5.setText("")
        self.TrafficLight_62C554_5.setText("")
        self.label_85.setText(QCoreApplication.translate("MainWindow", u"Apple Music", None))
        self.label_86.setText("")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0438\u0441\u043a", None))
        self.label_87.setText(QCoreApplication.translate("MainWindow", u"Playlist", None))
        self.pushButton_Album_3.setText(QCoreApplication.translate("MainWindow", u"Hip-Hop Replay", None))
        self.pushButton_Album_4.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0430\u0440\u0438\u043d\u0430 \u0438\u0441\u0442\u043e\u043c\u0438\u043d\u0430 \u0440\u0435\u043a...", None))
        self.pushButton_Album_5.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0430\u0440\u0438\u043d\u0430 \u0438\u0441\u0442\u043e\u043c\u0438\u043d\u0430 \u0440\u0435\u043a...", None))
        self.imageAlbum.setText("")
        self.nameAlbum.setText(QCoreApplication.translate("MainWindow", u"Hip-Hop Replay", None))
        self.applemusic.setText(QCoreApplication.translate("MainWindow", u"Apple Music Hip Hop/Rap", None))
        self.des.setText(QCoreApplication.translate("MainWindow", u"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries", None))
        self.playButton.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.continue_2.setText(QCoreApplication.translate("MainWindow", u"Continue", None))
        self.shuffleButton.setText(QCoreApplication.translate("MainWindow", u"Shuffle", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"SONG", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"ARTIST", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"ALBUM", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"DUR", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Meek mill", None))
        self.label_45.setText("")
        self.label_46.setText("")
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"3:01", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Goding Bad (feat. Drake)", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Championships", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Travis scott", None))
        self.label_51.setText("")
        self.label_52.setText("")
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"2:56", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"HIGHEST IN THE ROOM", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"HIGHEST IN THE ROOM - Single", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"A$AP Rocky", None))
        self.label_57.setText("")
        self.label_58.setText("")
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"3:26", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Praise The Lord [feat. Skepta]", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"TESTING", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"Tyga", None))
        self.label_63.setText("")
        self.label_64.setText("")
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"3:53", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"Taste (feat. Offset)", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"Taste (feat. Offset) \u2013 Single", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"Post Malone", None))
        self.label_69.setText("")
        self.label_70.setText("")
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"2:30", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"Wow.", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"Wow. \u2013 Single", None))
        self.label_74.setText(QCoreApplication.translate("MainWindow", u"Fetty Wap", None))
        self.label_75.setText("")
        self.label_76.setText("")
        self.label_77.setText(QCoreApplication.translate("MainWindow", u"3:07", None))
        self.label_78.setText(QCoreApplication.translate("MainWindow", u"679 (feat . Morty)", None))
        self.label_79.setText(QCoreApplication.translate("MainWindow", u"Fetty Wap (Deluxe Edition)", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"SONG", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"ARTIST", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"ALBUM", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"DUR", None))
        self.back_4.setText("")
        self.playlist_4.setText(QCoreApplication.translate("MainWindow", u"Playlist", None))
        self.label_19.setText("")
        self.label_20.setText("")
        self.label_21.setText("")
        self.label_22.setText("")
        self.label_23.setText("")
        self.label_24.setText("")
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"The Box", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Roddy Ricch \u2013 Please Excuse Me For Being Antisocial", None))
        self.label_27.setText("")
        self.label_28.setText("")
    # retranslateUi

